name: ChromaQuantExtension 
channels:
  - conda-forge
dependencies:
  - pandas~=2.2.2
	- molmass~=2024.5.24
	- numpy~=1.26.4
	- chemformula~=1.3.1
	- scipy~=1.13.1
	- ttkthemes~=3.2.2
	- pillow~=10.3.0
	- plotly~=5.22.0
	- pubchempy~=1.0.4
	- rdkit~=2024.3.5
	- XlsxWriter~=3.2.0
	- openpyxl~=3.1.5

